export const objectTypeOptions = [
    { value: 'digitalart', label: 'Digital Art' },
    { value: 'physicalart', label: 'Physical Art' },
    { value: 'digitalphysicalart', label: 'Digital Physical Art' },
];
export const aiGenerationOptions = [
    { value: 'full', label: 'Full' },
    { value: 'partial', label: 'Partial' },
    { value: 'none', label: 'None' },
];
export const arEnabledOptions = [
    { value: 'yes', label: 'Yes' },
    { value: 'no', label: 'No' },
];
export const nudityOptions = [
    { value: 'yes', label: 'Yes' },
    { value: 'no', label: 'No' },
];
export const categoryOptions = [
    { value: 'photography', label: 'Photography' },
    { value: 'painting', label: 'Painting' },
    { value: 'threed', label: 'Three D' },
    { value: 'video', label: 'Video' },
    { value: 'mixedmedia', label: 'Mixed Media' },
    { value: 'illustration', label: 'Illustration' },
    { value: 'collage', label: 'Collage' },
];
export const mediumOptions = [
    { value: 'acrylic', label: 'Acrylic' },
    { value: 'ai', label: 'AI' },
    { value: 'airbrush', label: 'Airbrush' },
    { value: 'albumensilver', label: 'Albumen Silver' },
    { value: 'algorithmic', label: 'Algorithmic' },
    { value: 'aluminium', label: 'Aluminium' },
    { value: 'appropriation', label: 'Appropriation' },
    { value: 'aquatint', label: 'Aquatint' },
    { value: 'assemblage', label: 'Assemblage' },
    { value: 'augmentedreality', label: 'Augmented Reality' },
    { value: 'ballpoint', label: 'Ballpoint' },
    { value: 'bas-relief', label: 'Bas-relief' },
    { value: 'basalt', label: 'Basalt' },
    { value: 'binder', label: 'Binder' },
    { value: 'blockchain', label: 'Blockchain' },
    { value: 'board', label: 'Board' },
    { value: 'brass', label: 'Brass' },
    { value: 'bronze', label: 'Bronze' },
    { value: 'brush', label: 'Brush' },
    { value: 'burlap', label: 'Burlap' },
    { value: 'bw', label: 'B&W' },
    { value: 'cable', label: 'Cable' },
    { value: 'cameo', label: 'Cameo' },
    { value: 'canvas', label: 'Canvas' },
    { value: 'carbonfiber', label: 'Carbon Fiber' },
    { value: 'card', label: 'Card' },
    { value: 'cardboard', label: 'Cardboard' },
    { value: 'casein', label: 'Casein' },
    { value: 'cement', label: 'Cement' },
    { value: 'ceramic', label: 'Ceramic' },
    { value: 'ceramics', label: 'Ceramics' },
    { value: 'chalk', label: 'Chalk' },
    { value: 'charcoal', label: 'Charcoal' },
    { value: 'chisel', label: 'Chisel' },
    { value: 'clay', label: 'Clay' },
    { value: 'cliché-verre', label: 'Cliché-verre' },
    { value: 'cloth', label: 'Cloth' },
    { value: 'coal', label: 'Coal' },
    { value: 'collage', label: 'Collage' },
    { value: 'collotype', label: 'Collotype' },
    { value: 'color', label: 'Color' },
    { value: 'coloredmarkers', label: 'Colored Markers' },
    { value: 'coloredpencils', label: 'Colored Pencils' },
    { value: 'colorvarnish', label: 'Color Varnish' },
    { value: 'concrete', label: 'Concrete' },
    { value: 'conte', label: 'Conte' },
    { value: 'copper', label: 'Copper' },
    { value: 'cotton', label: 'Cotton' },
    { value: 'crayon', label: 'Crayon' },
    { value: 'ctype', label: 'C-type' },
    { value: 'decoupage', label: 'Decoupage' },
    { value: 'digital', label: 'Digital' },
    { value: 'drawing', label: 'Drawing' },
    { value: 'drypoint', label: 'Drypoint' },
    { value: 'dust', label: 'Dust' },
    { value: 'dye', label: 'Dye' },
    { value: 'elephantdung', label: 'Elephant Dung' },
    { value: 'embroidery', label: 'Embroidery' },
    { value: 'emulsion', label: 'Emulsion' },
    { value: 'enamel', label: 'Enamel' },
    { value: 'encaustic', label: 'Encaustic' },
    { value: 'engraving', label: 'Engraving' },
    { value: 'environmental', label: 'Environmental' },
    { value: 'etching', label: 'Etching' },
    { value: 'fabric', label: 'Fabric' },
    { value: 'fabricstraps', label: 'Fabric Straps' },
    { value: 'fat', label: 'Fat' },
    { value: 'feather', label: 'Feather' },
    { value: 'felt-tippen', label: 'Felt-tip Pen' },
    { value: 'felt', label: 'Felt' },
    { value: 'fiber', label: 'Fiber' },
    { value: 'fiberboard', label: 'Fiberboard' },
    { value: 'fiberglass', label: 'Fiberglass' },
    { value: 'film', label: 'Film' },
    { value: 'flashlight', label: 'Flashlight' },
    { value: 'fluorescentpaint', label: 'Fluorescent Paint' },
    { value: 'found', label: 'Found' },
    { value: 'fractal', label: 'Fractal' },
    { value: 'fresco', label: 'Fresco' },
    { value: 'frottage', label: 'Frottage' },
    { value: 'fullspectrum', label: 'Full Spectrum' },
    { value: 'gelatin', label: 'Gelatin' },
    { value: 'gelatinsilverprint', label: 'Gelatin Silver Print' },
    { value: 'gesso', label: 'Gesso' },
    { value: 'giclee', label: 'Giclée' },
    { value: 'gilt', label: 'Gilt' },
    { value: 'glass', label: 'Glass' },
    { value: 'glitter', label: 'Glitter' },
    { value: 'gloss', label: 'Gloss' },
    { value: 'gold', label: 'Gold' },
    { value: 'goldleaf', label: 'Gold Leaf' },
    { value: 'gouache', label: 'Gouache' },
    { value: 'graffiti', label: 'Graffiti' },
    { value: 'granite', label: 'Granite' },
    { value: 'graphite', label: 'Graphite' },
    { value: 'graphitepencil', label: 'Graphite Pencil' },
    { value: 'grattage', label: 'Grattage' },
    { value: 'greenstone', label: 'Greenstone' },
    { value: 'grisaille', label: 'Grisaille' },
    { value: 'gumarabic', label: 'Gum Arabic' },
    { value: 'hematite', label: 'Hematite' },
    { value: 'hemp', label: 'Hemp' },
    { value: 'hologram', label: 'Hologram' },
    { value: 'horns', label: 'Horns' },
    { value: 'household', label: 'Household' },
    { value: 'indianink', label: 'Indian Ink' },
    { value: 'ink', label: 'Ink' },
    { value: 'intaglio', label: 'Intaglio' },
    { value: 'interactive', label: 'Interactive' },
    { value: 'iron', label: 'Iron' },
    { value: 'ironplate', label: 'Iron Plate' },
    { value: 'ivory', label: 'Ivory' },
    { value: 'japanesepaper', label: 'Japanese Paper' },
    { value: 'jute', label: 'Jute' },
    { value: 'kinetic', label: 'Kinetic' },
    { value: 'lacquer', label: 'Lacquer' },
    { value: 'laidpaper', label: 'Laid Paper' },
    { value: 'latex', label: 'Latex' },
    { value: 'lavis', label: 'Lavis' },
    { value: 'leadpoint', label: 'Lead Point' },
    { value: 'leather', label: 'Leather' },
    { value: 'led', label: 'LED' },
    { value: 'lemon', label: 'Lemon' },
    { value: 'lenticular', label: 'Lenticular' },
    { value: 'lightbox', label: 'Lightbox' },
    { value: 'lightbulb', label: 'Lightbulb' },
    { value: 'lights', label: 'Lights' },
    { value: 'linen', label: 'Linen' },
    { value: 'linocut', label: 'Linocut' },
    { value: 'linocutb&w', label: 'Linocut B&W' },
    { value: 'linocutcolor', label: 'Linocut Color' },
    { value: 'linocuts', label: 'Linocuts' },
    { value: 'linoleum', label: 'Linoleum' },
    { value: 'lithograph', label: 'Lithograph' },
    { value: 'lithography', label: 'Lithography' },
    { value: 'magna', label: 'Magna' },
    { value: 'magnets', label: 'Magnets' },
    { value: 'mahoganypanel', label: 'Mahogany Panel' },
    { value: 'majolica', label: 'Majolica' },
    { value: 'manipulated', label: 'Manipulated' },
    { value: 'mappins', label: 'Map Pins' },
    { value: 'marble', label: 'Marble' },
    { value: 'marker', label: 'Marker' },
    { value: 'maskingtape', label: 'Masking Tape' },
    { value: 'masonite', label: 'Masonite' },
    { value: 'metal', label: 'Metal' },
    { value: 'metalpoint', label: 'Metal Point' },
    { value: 'mezzotint', label: 'Mezzotint' },
    { value: 'mixedmedia', label: 'Mixed Media' },
    { value: 'mixedtechnique', label: 'Mixed Technique' },
    { value: 'monotype', label: 'Monotype' },
    { value: 'mosaic', label: 'Mosaic' },
    { value: 'mosaïque', label: 'Mosaïque' },
    { value: 'mural', label: 'Mural' },
    { value: 'music', label: 'Music' },
    { value: 'musicpaper', label: 'Music Paper' },
    { value: 'nails', label: 'Nails' },
    { value: 'neon', label: 'Neon' },
    { value: 'oak', label: 'Oak' },
    { value: 'objettrouve', label: 'Objet Trouvé' },
    { value: 'obsidian', label: 'Obsidian' },
    { value: 'oil', label: 'Oil' },
    { value: 'oilcloth', label: 'Oilcloth' },
    { value: 'onyx', label: 'Onyx' },
    { value: 'paint', label: 'Paint' },
    { value: 'paintedmetal', label: 'Painted Metal' },
    { value: 'panel', label: 'Panel' },
    { value: 'paper', label: 'Paper' },
    { value: 'papermache', label: 'Papier-mâché' },
    { value: 'papier-pelle', label: 'Papier-pelle' },
    { value: 'papyrus', label: 'Papyrus' },
    { value: 'parchment', label: 'Parchment' },
    { value: 'pastel', label: 'Pastel' },
    { value: 'pebbles', label: 'Pebbles' },
    { value: 'pen', label: 'Pen' },
    { value: 'pencil', label: 'Pencil' },
    { value: 'penink', label: 'Pen & Ink' },
    { value: 'pergament', label: 'Pergament' },
    { value: 'photo', label: 'Photo' },
    { value: 'photogram', label: 'Photogram' },
    { value: 'photographicpaper', label: 'Photographic Paper' },
    { value: 'photography', label: 'Photography' },
    { value: 'photogravure', label: 'Photogravure' },
    { value: 'photomontage', label: 'Photomontage' },
    { value: 'photomosaic', label: 'Photomosaic' },
    { value: 'piano', label: 'Piano' },
    { value: 'pigment', label: 'Pigment' },
    { value: 'pinhole', label: 'Pinhole' },
    { value: 'plaster', label: 'Plaster' },
    { value: 'plastic', label: 'Plastic' },
    { value: 'plates', label: 'Plates' },
    { value: 'platinum', label: 'Platinum' },
    { value: 'plexiglas', label: 'Plexiglas' },
    { value: 'plugsocket', label: 'Plug Socket' },
    { value: 'plywood', label: 'Plywood' },
    { value: 'poetry', label: 'Poetry' },
    { value: 'polaroid', label: 'Polaroid' },
    { value: 'polyester', label: 'Polyester' },
    { value: 'polymer', label: 'Polymer' },
    { value: 'polymerpaint', label: 'Polymer Paint' },
    { value: 'polystyrene', label: 'Polystyrene' },
    { value: 'poplar', label: 'Poplar' },
    { value: 'porcelain', label: 'Porcelain' },
    { value: 'postcard', label: 'Postcard' },
    { value: 'pottery', label: 'Pottery' },
    { value: 'precious', label: 'Precious' },
    { value: 'print', label: 'Print' },
    { value: 'printedbrochure', label: 'Printed Brochure' },
    { value: 'pyroxylin', label: 'Pyroxylin' },
    { value: 'varnish', label: 'Varnish' },
    { value: 'vector', label: 'Vector' },
    { value: 'vellum', label: 'Vellum' },
    { value: 'video', label: 'Video' },
    { value: 'vinyl', label: 'Vinyl' },
    { value: 'vitrage', label: 'Vitrage' },
    { value: 'ready-made', label: 'Ready-made' },
    { value: 'recorderwithcassette', label: 'Recorder with Cassette' },
    { value: 'resin', label: 'Resin' },
    { value: 'robotics', label: 'Robotics' },
    { value: 'rubber', label: 'Rubber' },
    { value: 'sand', label: 'Sand' },
    { value: 'sandStone', label: 'Sand Stone' },
    { value: 'sanguine', label: 'Sanguine' },
    { value: 'satin', label: 'Satin' },
    { value: 'scrapings', label: 'Scrapings' },
    { value: 'screenprint', label: 'Screenprint' },
    { value: 'screenprinting', label: 'Screenprinting' },
    { value: 'sculpting', label: 'Sculpting' },
    { value: 'sepia', label: 'Sepia' },
    { value: 'shell', label: 'Shell' },
    { value: 'silk', label: 'Silk' },
    { value: 'silkscreen', label: 'Silkscreen' },
    { value: 'silver', label: 'Silver' },
    { value: 'silverpoint', label: 'Silverpoint' },
    { value: 'sound', label: 'Sound' },
    { value: 'sponge', label: 'Sponge' },
    { value: 'spraypaint', label: 'Spraypaint' },
    { value: 'stainedglass', label: 'Stained Glass' },
    { value: 'steel', label: 'Steel' },
    { value: 'stencil', label: 'Stencil' },
    { value: 'stone', label: 'Stone' },
    { value: 'string', label: 'String' },
    { value: 'stucco', label: 'Stucco' },
    { value: 'stump', label: 'Stump' },
    { value: 'tapestry', label: 'Tapestry' },
    { value: 'tar', label: 'Tar' },
    { value: 'taxidermy', label: 'Taxidermy' },
    { value: 'tempera', label: 'Tempera' },
    { value: 'terracotta', label: 'Terracotta' },
    { value: 'textile', label: 'Textile' },
    { value: 'timber', label: 'Timber' },
    { value: 'tin', label: 'Tin' },
    { value: 'travertine', label: 'Travertine' },
    { value: 'turquoise', label: 'Turquoise' },
    { value: 'tusche', label: 'Tusche' },
    { value: 'twine', label: 'Twine' },
    { value: 'wall', label: 'Wall' },
    { value: 'wallpaper', label: 'Wallpaper' },
    { value: 'wash', label: 'Wash' },
    { value: 'watercolor', label: 'Watercolor' },
    { value: 'wax', label: 'Wax' },
    { value: 'waxpastel', label: 'Wax Pastel' },
    { value: 'white', label: 'White' },
    { value: 'whitewash', label: 'Whitewash' },
    { value: 'wine', label: 'Wine' },
    { value: 'wire', label: 'Wire' },
    { value: 'wood', label: 'Wood' },
    { value: 'woodblockprint', label: 'Woodblock Print' },
    { value: 'woodcut', label: 'Woodcut' },
    { value: 'woodenchair', label: 'Wooden Chair' },
    { value: 'woodengraving', label: 'Wood Engraving' },
    { value: 'woodensled', label: 'Wooden Sled' },
    { value: 'wool', label: 'Wool' },
    { value: 'zinc', label: 'Zinc' },
];
export const styleOptions = [
    { value: 'abstract', label: 'Abstract' },
    { value: 'abstractexpressionism', label: 'Abstract Expressionism' },
    { value: 'artdeco', label: 'Art Deco' },
    { value: 'conceptual', label: 'Conceptual' },
    { value: 'cubism', label: 'Cubism' },
    { value: 'dada', label: 'Dada' },
    { value: 'documentary', label: 'Documentary' },
    { value: 'expressionism', label: 'Expressionism' },
    { value: 'figurative', label: 'Figurative' },
    { value: 'fineart', label: 'Fine Art' },
    { value: 'folk', label: 'Folk' },
    { value: 'illustration', label: 'Illustration' },
    { value: 'impressionism', label: 'Impressionism' },
    { value: 'minimalism', label: 'Minimalism' },
    { value: 'modern', label: 'Modern' },
    { value: 'photorealism', label: 'Photorealism' },
    { value: 'popart', label: 'Pop Art' },
    { value: 'portraiture', label: 'Portraiture' },
    { value: 'realism', label: 'Realism' },
    { value: 'streetart', label: 'Street Art' },
    { value: 'surrealism', label: 'Surrealism' },
];
export const cultureOptions = [
    { value: 'african', label: 'African' },
    { value: 'centralasian', label: 'Central Asian' },
    { value: 'eastasian', label: 'East Asian' },
    { value: 'islamic', label: 'Islamic' },
    { value: 'latinamerican', label: 'Latin American' },
    { value: 'nativeamerican', label: 'Native American' },
    { value: 'oceanic', label: 'Oceanic' },
    { value: 'persian', label: 'Persian' },
    { value: 'southasian', label: 'South Asian' },
    { value: 'southeastasian', label: 'Southeast Asian' },
    { value: 'western', label: 'Western' },
];
export const moodOptions = [
    { value: 'admiration', label: 'Admiration' },
    { value: 'absorbing', label: 'Absorbing' },
    { value: 'amusement', label: 'Amusement' },
    { value: 'adoration', label: 'Adoration' },
    { value: 'awe', label: 'Awe' },
    { value: 'anxiety', label: 'Anxiety' },
    { value: 'boredom', label: 'Boredom' },
    { value: 'brooding', label: 'Brooding' },
    { value: 'calmness', label: 'Calmness' },
    { value: 'chills', label: 'Chills' },
    { value: 'chaotic', label: 'Chaotic' },
    { value: 'connectedness', label: 'Connectedness' },
    { value: 'cosmic', label: 'Cosmic' },
    { value: 'confusion', label: 'Confusion' },
    { value: 'dread', label: 'Dread' },
    { value: 'distaste', label: 'Distaste' },
    { value: 'disgust', label: 'Disgust' },
    { value: 'dreary', label: 'Dreary' },
    { value: 'disorienting', label: 'Disorienting' },
    { value: 'dreamy', label: 'Dreamy' },
    { value: 'desire', label: 'Desire' },
    { value: 'elegant', label: 'Elegant' },
    { value: 'humorous', label: 'Humorous' },
    { value: 'intimate', label: 'Intimate' },
    { value: 'intricate', label: 'Intricate' },
    { value: 'love', label: 'Love' },
    { value: 'lively', label: 'Lively' },
    { value: 'mystical', label: 'Mystical' },
    { value: 'mysterious', label: 'Mysterious' },
    { value: 'nostalgia', label: 'Nostalgia' },
    { value: 'ornate', label: 'Ornate' },
    { value: 'psychedelic', label: 'Psychedelic' },
    { value: 'serenity', label: 'Serenity' },
    { value: 'sadness', label: 'Sadness' },
    { value: 'sensual', label: 'Sensual' },
    { value: 'spiritual', label: 'Spiritual' },
    { value: 'strange', label: 'Strange' },
    { value: 'striking', label: 'Striking' },
    { value: 'tragic', label: 'Tragic' },
    { value: 'tense', label: 'Tense' },
    { value: 'vibrant', label: 'Vibrant' },
    { value: 'violent', label: 'Violent' },
    { value: 'wonder', label: 'Wonder' },
    { value: 'whimsical', label: 'Whimsical' },
];
export const orientationOptions = [
    { value: 'horizontal', label: 'Horizontal' },
    { value: 'vertical', label: 'Vertical' },
    { value: 'square', label: 'Square' },
];

export const shortcutsOptions = [
    { name: 'hideNudity', label: 'Hide Nudity' },
    { name: 'hideAI', label: 'Hide AI' },
    { name: 'photography', label: 'Photography' },
    { name: 'animation', label: 'Animation' },
    { name: 'physicalArt', label: 'Physical Art' },
    { name: 'digitalArt', label: 'Digital Art' },
    { name: 'includeSold', label: 'Include Sold' },
    { name: 'hasBTS', label: 'Has BTS' },
];

export const subTitlesReviewOptions = [
    { name: 'shortcuts', label: 'Filters' },
    { name: 'licenses', label: 'Artwork Price' },
    { name: 'culture', label: 'Culture' },
    { name: 'mood', label: 'Mood' },
    { name: 'orientation', label: 'Orientation' },
    { name: 'colors', label: 'Colors' },
    { name: 'precision', label: 'Precision' },
    { name: 'objectType', label: 'Object Type' },
    { name: 'tags', label: 'Tags' },
    { name: 'collections', label: 'Collections' },
    { name: 'aiGeneration', label: 'AI generation' },
    { name: 'arEnabled', label: 'AR enabled' },
    { name: 'nudity', label: 'Nudity' },
    { name: 'category', label: 'Category' },
    { name: 'medium', label: 'Medium' },
    { name: 'style', label: 'Style' },
    { name: 'subject', label: 'Subject' },
    { name: 'name', label: 'Name' },
    { name: 'nationality', label: 'Nationality' },
    { name: 'residence', label: 'Residence' },
    { name: 'wallets', label: 'Wallets' },
    { name: 'nft', label: 'Digital Collectible' },
    { name: 'print', label: 'Print' },
];

export const licensesOptions = [
    { name: 'nft', label: 'Digital Collectible' },
    { name: 'print', label: 'Print' },
];
